In [1]:
print("Hello, world")

Hello, world


In [6]:

import numpy as np

a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(axis = 0)
mean_a




array([2. , 8.4])

In [20]:
import numpy as np

a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
mean_a = a.mean(axis = 0)
b = a- mean_a
b


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [14]:
import numpy as np

a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])


b = np.array([a[i][0] for i in range(len(a))])
c = np.array([a[i][1] for i in range(len(a))])

print(b)
print(c)

print(np.dot(b,c) / (len(a)-1))

[1 2 3 3 1]
[ 6  8 11 10  7]
23.0
